### ISSUE TITLE
Integrate pagespeed with ngrok

### ISSUE THREAD

**Issue by DracoBlue** [nikita-kit/generator-nikita#1]
Currently pagespeed works only with external urls. With something like http://ngrok.com, we can test pagespeed of local urls, too!

Guide how to get it working with ngrok may be found here http://www.jamescryer.com/2014/06/12/grunt-pagespeed-and-ngrok-locally-testing/

**Comment by axten** [comment]
pagespeed is outdated so its better to use chrome dev tools
