### ISSUE TITLE
proposal to remove "prefer-const" from eslint error list

### ISSUE THREAD

**Issue by TheOriginalArkless** [nikita-kit/generator-nikita#142]
Problem case destructuring:

`            let {
                validationState,
                epgFocusDayIndex,
                epgFocusTimeIndex,
                epgFocusEventIndex,
                columns,
                focusedDay,
            } = loadNavigationDataValidated(previousState);`

Some of these variables change, some don't.
Splitting up the destructuring into multiple declarations reduces readability.

eslint rule that that is set to throw an error: prefer-const

**Comment by axten** [comment]
should be fixed in eslint-config-niktia 3.0.0
