### ISSUE TITLE
fix dependencies to rem-include by nikita.css

### ISSUE THREAD

**Issue by DracoBlue** [nikita-kit/generator-nikita#16]
Currently, it's not possible to disable the rem-mixin, because there is the button.scss (see hoffgk's crash log here https://gist.github.com/hoffigk/732a2a9945692525e604 ), which requires this mixin:

![bildschirmfoto 2015-02-16 um 15 00 12](https://cloud.githubusercontent.com/assets/35926/6213102/a40b0a04-b5ec-11e4-8fa4-c4cce5f33f5a.png)

We have three ways to fix this: 

* automagically include the rem-mixin, if we use it somewhere
* always include the mixin
* get rid of the rem-mixin usage

@rastersysteme what do you think?

**Comment by rastersysteme** [comment]
I removed all includes because we don't need the px-to-rem-mixin anymore. All major browsers support the unit _rem_.
