### ISSUE TITLE
Warning: Unable to create directory "/tmp/tmp/grunticon-tmp" with "grunt-grunticon": "~1.2.13"

### ISSUE THREAD

**Issue by hoffigk** [nikita-kit/generator-nikita#18]
"grunt-grunticon": "~1.2.13" has an fixed tmpPath and it is only possibly to set an custom tmpPath via TMPDIR:

shell> cd nikita-app/
shell> TMPDIR=tmp/ grunt

This works for me, but i don't wont it.

I have an Ubuntu 14.04 on DigitalOcean installed and get the wrong temp dir. On my vagrant box all is fine.

https://github.com/filamentgroup/grunticon/commit/a43cb96d8eba4fcfae7653d33e1865c7c35194fb has the new option tmpPath, that allows to set the right tmpPath inside the nikita app. 

Changing to "grunt-grunticon": "~1.6.0" and modify the grunticon options in Gruntfile.js from:

options: {
    cssprefix: '%icon-',
    datapngcss: '_icons-data-png.scss',
    datasvgcss: '_icons-data-svg.scss',
    urlpngcss: '_icons-fallback.scss',
    tmpDir: '<%= paths.tmp %>/grunticon-tmp',
},

to:

options: {
    cssprefix: '%icon-',
    datapngcss: '_icons-data-png.scss',
    datasvgcss: '_icons-data-svg.scss',
    urlpngcss: '_icons-fallback.scss',
    tmpPath: '<%= paths.tmp %>',
    tmpDir: '/grunticon-tmp',
},

works for me.

**Comment by DracoBlue** [comment]
Thanks. Fixed ;)
