### ISSUE TITLE
string-replace task only processes first svg file

### ISSUE THREAD

**Issue by rastersysteme** [nikita-kit/generator-nikita#22]
At the moment our replacement in the string-replace-task looks like this:
```
pattern: /^\.%bg-data-svg-/g,
replacement: '%bg-data-svg-'
```

The output looks like this:
```
%bg-data-svg-foo1 { …}
.%bg-data-svg-foo2 { …}
.%bg-data-svg-foo3 { …}
````

This is wrong because we don't want the leading dot.

So, what about:
```
pattern: /.%bg-data-svg-/g,
replacement: '%bg-data-svg-'
```

**Comment by DracoBlue** [comment]
Yes, good point

Am Dienstag, 24. März 2015 schrieb Stephan Zavodny :

> At the moment our replacement in the string-replace-task looks like this:
>
> pattern: /^\.%bg-data-svg-/g,
> replacement: '%bg-data-svg-'
>
> The output looks like this:
>
> %bg-data-svg-foo1 { …}
> .%bg-data-svg-foo2 { …}
> .%bg-data-svg-foo3 { …}
>
> This is wrong because we don't want the leading dot.
>
> So, what about:
>
> pattern: /.%bg-data-svg-/g,
> replacement: '%bg-data-svg-'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nikita-kit/generator-nikita/issues/22>.
>


-- 

  http://dracoblue.net

**Comment by DracoBlue** [comment]
@rastersysteme  Can you tag an 1.0.1 for this fix?

**Comment by rastersysteme** [comment]
done.
