### ISSUE TITLE
Add `grunt imagemin:source`

### ISSUE THREAD

**Issue by DracoBlue** [nikita-kit/generator-nikita#32]
In a project of mine, the imagemin:dist takes **32 MINUTES**. Even in case of #31 (moving imagemin to dist), this would take very long for every dist build.

What do you think of something like: `imagemin:source` (with optimizationLevel: 7):

``` console
$ grunt imagemin:source
Running "imagemin:source" (imagemin) task
Minified 403 images (saved 72.33 MB)

Done, without errors.

Execution Time (2015-08-31 15:06:52 UTC)
imagemin:source  1944.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 1945s
```

This would optimize the images within the source-Folder. Team members would be adviced to run imagemin:source when they add new images. If necessary, we can keep imagemin in dist-Process, to ensure that images in dist builds are 100% optimized.

An other option would be, to run: `imagemin:dist` with `optimizationLevel: 3` (the default, means: 16 trials instead of 240 trials with `optimizationLevel: 7`). In my testcase (403 images with 155MB) the execution time decreased from 32 Minutes to 4 Minutes.

// cc @rastersysteme @lhtdesignde

**Comment by axten** [comment]
see #116
